query PaginatedStudents($pageIndex: Int, $take: Int, $studentId: String) {
  paginatedStudents(pageIndex: $pageIndex, take: $take, studentId: $studentId) {
    totalCount
    students {
      ...studentInfo
    }
  }
}
