query TrainingFields {
  trainingFields {
    id
    name
    faculty {
      id
      name
      classes {
        id
        name
      }
    }
    trainingSystem {
      id
      name
    }
    trainingType {
      id
      name
    }
    courses {
      id
      name
    }
    trainingFieldToProgramToCourse {
      course {
        id
        name
      }
      trainingProgram {
        id
        name
      }
    }
  }
}
