export * from "./auth.resolver";
export * from "./faculties.resolver";
export * from "./lecturers.resolver";
export * from "./students.resolver";
export * from "./classes.resolver";
export * from "./courses.resolver";
export * from "./educational-field.resolver";
export * from "./educational-system.resolver";
export * from "./educational-program.resolver";
