fragment studentInfo on Student {
  id
  name
  createdAt
  studentType
  studyStatus
  gender
  dob
  pob
  ethnicity
  identification
  religion
  area
  priority
  province
  district
  country
  permanentAddress
  numberPhone
  email
  address
  fatherName
  motherName
  relativeName
  relativeNumberPhone
  relativeAddress
  class {
    ...classInfo
  }
  position {
    ...positionInfo
  }
  course {
    ...courseInfo
  }
  faculty {
    ...facultyInfo
  }
}
